import {InfoPage} from '@/components/info-page';
import {SupportContact} from '@/components/support-contact';
export const dynamic='force-dynamic';
export default function Help(){return <InfoPage title="A little help finding your car." intro="Start with what matters. MotorScout keeps your requirements visible while you browse.">
<section><h2>Start a search</h2><p>Use filters for a make, model, trim, budget and mileage. Ask Scout in a sentence or use follow-up shortcuts to narrow your collected cars. Your current requirements appear above the cars.</p><p>Sign in to use the free search beta. MotorScout provides limited shared marketplace access while its free allowance lasts; you do not need to enter a personal API key. Available sources, result counts and coverage vary. If the allowance is exhausted, your collected and saved cars remain available.</p></section>
<section><h2>Why fewer cars than expected?</h2><p>Some models and specifications are rare. A source may omit the trim, color or equipment needed to confirm a match. Provider limits and regional coverage also affect results. MotorScout does not invent cars or silently relax your requirements to reach a target count.</p><p>Use Check more marketplaces for available regional batches. Sources shows which providers returned records; this is not a claim that every website or vehicle was searched.</p></section>
<section><h2>Understand a price</h2><p>Feed prices are not guaranteed purchase offers. A source-checked price is labeled separately. Known savings, deposits, financing payments and accessory amounts are withheld until a full price is established. Taxes, registration, shipping and undisclosed fees can change your total.</p><p>The red, yellow and green comparison uses similar asking prices in the collected inventory. It is not an appraisal or a prediction of the sale price. When evidence is insufficient, no rating is shown.</p></section>
<section><h2>Save, compare and start over</h2><p>Use Save on a car, then remove it from Saved when you are done. Compare holds up to three cars, with a remove control for each. Reset chat clears the conversation while keeping your cars and filters. New search resets the current search; saved cars stay saved.</p></section>
<section><h2>Saved searches and alerts</h2><p>You can save exact requirements and reuse their filters anytime. Check now becomes available only when automatic checks are activated and a search is due. The Saved searches screen shows whether automatic checks are currently active. Enable daily checks for each search you want watched. Email delivery is separate and remains unavailable until a sending service is connected; you are never subscribed by default.</p><p>Background checks, when activated, cover supported inventory feeds and limited daily capacity, not every marketplace listing. You can pause or remove a saved search.</p></section>
<section><h2>Support</h2><SupportContact/></section>
</InfoPage>}
