import assert from 'node:assert/strict';
import {trimMatches} from '../lib/vehicle-identity';
import {availableComparisonIds,filterSchema,matches,deduplicate,relaxed,rank,type Listing} from '../lib/domain';
const base:Listing={id:'test-1',vin:'12345678901234567',title:'Test fixture — never shown in the app',make:'BMW',model:'3 Series',trim:'M340i',year:2021,price:34000,miles:39000,state:'CO',city:'Test',source:'test',url:'https://example.test/car/1',photo:null,seller:'private',drive:'AWD',titleStatus:'unknown',condition:'used',history:'unknown',fees:1500,checkedAt:new Date().toISOString(),sourceUpdatedAt:null,concerns:[],comparables:[],median:null,reason:'',total:35500};
const f=filterSchema.parse({maxPrice:35000,maxMiles:40000,state:'CO'});
assert.equal(trimMatches('Premium Plus quattro','Premium'),false);
assert.equal(trimMatches('Premium Plus quattro','Premium Plus'),true);
assert.equal(trimMatches('Prestige quattro','Prestige'),true);
assert.equal(trimMatches('Competition','Competition Sport'),false);
assert.equal(filterSchema.parse({make:'ford',model:'f150'}).model,'F-150');
assert.equal(filterSchema.parse({model:'ford f150'}).make,'Ford');
assert.equal(filterSchema.parse({model:'ford f150'}).model,'F-150');
assert.equal(filterSchema.parse({make:'Custom',model:'Rare Model',trim:'Special'}).model,'Rare Model');
assert.equal(matches({...base,make:'Ford',model:'F-150'},filterSchema.parse({make:'ford',model:'f150'})),true);
assert.equal(matches({...base,make:'Ford',model:'F-150 Lightning'},filterSchema.parse({make:'ford',model:'f150'})),false);
assert.equal(matches(base,f),false,'disclosed fees count against budget');
assert.equal(matches({...base,fees:0},f),true);
assert.equal(matches({...base,fees:0,miles:null},f),false,'unknown mileage cannot pass limit');
assert.equal(matches({...base,fees:0}, {...f,cleanTitle:true}),false,'unknown title excluded');
assert.equal(matches({...base,fees:0}, {...f,seller:'dealer'}),false);
assert.equal(deduplicate([base,{...base,id:'second-source',url:'https://example.test/car/2'}]).length,1,'VIN deduplication');
assert.equal(relaxed(f,{...f,maxPrice:40000}),true);
assert.equal(relaxed(f,{...f,maxMiles:30000}),false);
assert.equal(relaxed(f,{...f,state:''}),true);
const rows=Array.from({length:8},(_,i)=>({...base,id:`test-${i}`,vin:String(i).padStart(17,'0'),url:`https://example.test/${i}`,price:30000+i*500,fees:0}));
assert.equal(rank(rows,rows,f)[0].median,null,'unknown history suppresses unsupported price evidence');
const known=rows.map(x=>({...x,titleStatus:'clean',history:'no accidents disclosed'}));
assert.ok(rank(known,known,f)[0].median!==null,'sufficient matched evidence yields a median');
assert.equal(rank(known,known,{...f,shippingAllowance:10000}).length,0,'shipping reserve counts against budget');
console.log('PASS: 11 filter, fee, shipping, duplicate, confirmation, and comparable-evidence checks');
assert.deepEqual(availableComparisonIds([base],['missing-1',base.id,'missing-2',base.id]),[base.id],'unavailable and repeated cars cannot consume comparison slots');
assert.deepEqual(availableComparisonIds([base,{...base,id:'saved-car'}],['saved-car',base.id]),['saved-car',base.id],'saved comparisons retain selection order');

const target=known[0];
const availableComps=known.slice(1,5);
const unavailableComp={...known[5],priceReview:{status:'unavailable' as const,checkedAt:new Date().toISOString(),reportedPrice:known[5].price,note:'The seller reports this listing unavailable.'}};
assert.equal(rank([target],[...availableComps,unavailableComp],f)[0].median,null,'an unavailable listing cannot supply the fifth comparable even without a price warning');
assert.equal(rank([target],[...availableComps,known[5]],f)[0].median,31500,'five available condition-matched listings still support a median');
