import assert from 'node:assert/strict';
import {trimMatches} from '../lib/vehicle-identity';
import {availableComparisonIds,filterSchema,matches,deduplicate,relaxed,rank,type Listing} from '../lib/domain';
const base:Listing={id:'test-1',vin:'12345678901234567',title:'Test fixture — never shown in the app',make:'BMW',model:'3 Series',trim:'M340i',year:2021,price:34000,miles:39000,state:'CO',city:'Test',source:'test',url:'https://example.test/car/1',photo:null,seller:'private',drive:'AWD',titleStatus:'unknown',condition:'used',history:'unknown',fees:1500,checkedAt:new Date().toISOString(),sourceUpdatedAt:null,concerns:[],comparables:[],median:null,reason:'',total:35500};
const f=filterSchema.parse({maxPrice:35000,maxMiles:40000,state:'CO'});
assert.equal(trimMatches('Premium Plus quattro','Premium'),false);
assert.equal(trimMatches('Premium Plus quattro','Premium Plus'),true);
assert.equal(trimMatches('Prestige quattro','Prestige'),true);
assert.equal(trimMatches('Competition','Competition Sport'),false);
assert.equal(filterSchema.parse({make:'ford',model:'f150'}).model,'F-150');
assert.equal(filterSchema.parse({model:'ford f150'}).make,'Ford');
assert.equal(filterSchema.parse({model:'ford f150'}).model,'F-150');
assert.equal(filterSchema.parse({make:'Custom',model:'Rare Model',trim:'Special'}).model,'Rare Model');
assert.equal(matches({...base,make:'Ford',model:'F-150'},filterSchema.parse({make:'ford',model:'f150'})),true);
assert.equal(matches({...base,make:'Ford',model:'F-150 Lightning'},filterSchema.parse({make:'ford',model:'f150'})),false);
assert.equal(matches(base,f),false,'disclosed fees count against budget');
assert.equal(matches({...base,fees:0},f),true);
assert.equal(matches({...base,fees:0,miles:null},f),false,'unknown mileage cannot pass limit');
assert.equal(matches({...base,fees:0}, {...f,cleanTitle:true}),false,'unknown title excluded');
assert.equal(matches({...base,fees:0}, {...f,seller:'dealer'}),false);
assert.equal(deduplicate([base,{...base,id:'second-source',url:'https://example.test/car/2'}]).length,1,'VIN deduplication');
assert.equal(relaxed(f,{...f,maxPrice:40000}),true);
assert.equal(relaxed(f,{...f,maxMiles:30000}),false);
assert.equal(relaxed(f,{...f,state:''}),true);
const rows=Array.from({length:8},(_,i)=>({...base,id:`test-${i}`,vin:String(i).padStart(17,'0'),url:`https://example.test/${i}`,price:30000+i*500,fees:0}));
assert.equal(rank(rows,rows,f)[0].median,null,'unknown history suppresses unsupported price evidence');
const known=rows.map(x=>({...x,titleStatus:'clean',history:'no accidents disclosed'}));
assert.ok(rank(known,known,f)[0].median!==null,'sufficient matched evidence yields a median');
assert.equal(rank(known,known,{...f,shippingAllowance:10000}).length,0,'shipping reserve counts against budget');
console.log('PASS: 11 filter, fee, shipping, duplicate, confirmation, and comparable-evidence checks');
assert.deepEqual(availableComparisonIds([base],['missing-1',base.id,'missing-2',base.id]),[base.id],'unavailable and repeated cars cannot consume comparison slots');
assert.deepEqual(availableComparisonIds([base,{...base,id:'saved-car'}],['saved-car',base.id]),['saved-car',base.id],'saved comparisons retain selection order');

const target=known[0];
const availableComps=known.slice(1,5);
const unavailableComp={...known[5],priceReview:{status:'unavailable' as const,checkedAt:new Date().toISOString(),reportedPrice:known[5].price,note:'The seller reports this listing unavailable.'}};
assert.equal(rank([target],[...availableComps,unavailableComp],f)[0].median,null,'an unavailable listing cannot supply the fifth comparable even without a price warning');
assert.equal(rank([target],[...availableComps,known[5]],f)[0].median,31500,'five available condition-matched listings still support a median');

const oldOffer={...base,price:30000,checkedAt:'2026-09-27T00:00:00Z'};
const freshOffer={...base,price:34000,checkedAt:'2026-09-28T00:00:00Z'};
for(const rows of [[oldOffer,freshOffer],[freshOffer,oldOffer]]){
 const refreshed=deduplicate(rows)[0];
 assert.equal(refreshed.price,34000,'freshness for the same source URL precedes price sorting');
 assert.equal(refreshed.offers![0].price,34000);
}
assert.equal(deduplicate([freshOffer,{...freshOffer,price:35000}])[0].price,35000,'incoming same-time refresh wins');
const composite={...oldOffer,offers:[{source:'alternate',url:'https://alternate.example/car',price:31000,fees:null,checkedAt:oldOffer.checkedAt}]};
const alternate={...freshOffer,id:'alternate',source:'alternate',url:'https://alternate.example/car',price:36000};
assert.equal(deduplicate([composite,alternate])[0].offers!.find(offer=>offer.url===alternate.url)?.price,36000,'fresh alternate offer beats a cheaper composite summary');
assert.equal(deduplicate([{...freshOffer,offers:[{source:base.source,url:base.url,price:100,fees:null,checkedAt:freshOffer.checkedAt}]}])[0].offers![0].price,34000,'primary offer always reflects the full current record');

const mileageRange=filterSchema.parse({minMiles:30000,maxMiles:40000});
for(const miles of [30000,35000,40000])assert(matches({...base,miles},mileageRange),'both mileage bounds are inclusive');
for(const miles of [29999,40001,null])assert(!matches({...base,miles},mileageRange),'outside or unknown mileage cannot pass a range');
assert(!matches({...base,miles:null},filterSchema.parse({minMiles:0})),'even a zero minimum requires mileage evidence');
assert(matches({...base,miles:1000000},filterSchema.parse({minMiles:1000000})));
assert(matches({...base,miles:40000},filterSchema.parse({minMiles:40000,maxMiles:40000})),'equal bounds permit exact mileage');
assert.equal(filterSchema.parse({maxMiles:40000}).minMiles,null,'legacy saved filters gain an unset minimum');
assert.equal(filterSchema.parse({make:'ford',model:'f150',minMiles:1000}).model,'F-150','mileage validation preserves vehicle aliases');
for(const minMiles of [-1,1000001,1.5])assert(!filterSchema.safeParse({minMiles}).success);
const invertedRange=filterSchema.safeParse({minMiles:40001,maxMiles:40000});
assert(!invertedRange.success);assert.deepEqual(invertedRange.error.issues[0].path,['minMiles']);assert.match(invertedRange.error.issues[0].message,/Minimum mileage.*maximum mileage/);
assert(relaxed(mileageRange,{...mileageRange,minMiles:20000}),'lowering a minimum broadens requirements');
assert(relaxed(mileageRange,{...mileageRange,minMiles:null}),'removing a minimum broadens requirements');
assert(!relaxed(mileageRange,{...mileageRange,minMiles:35000}),'raising a minimum tightens requirements');
assert(!relaxed(filterSchema.parse({}),filterSchema.parse({minMiles:1000})),'adding a minimum tightens requirements');
