import assert from 'node:assert/strict';
import {engineMatches,engineFacts,providerEngineText,requestedEngineTerms} from '../lib/engine-specs';
import {normalizeMarketcheck} from '../lib/marketcheck';
import {normalizeAutoDev} from '../lib/autodev';
import {basic} from '../lib/basic-parser';
import {filterSchema,initialFilters,matches} from '../lib/domain';
import {localScoutRefinement} from '../lib/local-scout-command';
assert.deepEqual(requestedEngineTerms('find a supercherged Audi with a V-6'),['supercharged','v6']);
for(const description of ['5.0L V8','V-8 engine','V 8'])assert.equal(engineMatches({engineText:description},'V8'),true);
assert.equal(engineMatches({engineText:'8 cylinder'},'V8'),false,'cylinder count alone does not establish layout');
assert.equal(engineMatches({engineText:'V8'},'8-cylinder'),true);
assert.equal(engineMatches({engineText:'Twin-Turbo V6'},'turbocharged'),true);
assert.equal(engineMatches({engineText:'Turbo V6'},'twin turbo'),false);
assert.equal(engineMatches({engineText:'inline-six'},'I6'),true);
assert.equal(engineMatches({engineText:'H6'},'flat six'),true);
assert.equal(engineMatches({engineText:providerEngineText({engine_block:'V',cylinders:8})},'V8'),true);
assert.equal(engineMatches({evidenceText:'performance of a V8'},'V8'),false);
for(const description of ['not supercharged','supercharger available separately','V8 engine swap kit optional','No V8 engine','3.0T TFSI'])assert.equal(engineMatches({evidenceText:description},'supercharged'),false);
assert.equal(engineMatches({engineText:'V6',evidenceText:'V8'},'V8'),false);
assert.equal(engineMatches({engineText:'V6',evidenceText:'V8'},'V6'),false);
assert.equal(engineMatches({},'V8'),false);
const audi={make:'Audi',model:'S4',trim:'3.0T Premium Plus',year:2015};
assert.equal(engineMatches(audi,'supercharged'),true);
assert.equal(engineMatches({...audi,year:2018},'supercharged'),false);
assert.equal(engineMatches({...audi,model:'A4'},'supercharged'),false);
assert.equal(engineMatches({...audi,trim:'2.0T'},'supercharged'),false);
assert.equal(engineMatches({...audi,engineText:'Turbo V6'},'supercharged'),false);
assert.equal(engineMatches({...audi,evidenceText:'V8 engine swap'},'supercharged'),false);
assert.match(engineFacts(audi).basis,/Factory/);
assert.equal(providerEngineText({name:'V8',numberOfCylinders:8}),'V8\n8 cylinder');
const mc=normalizeMarketcheck({price:30000,vdp_url:'https://example.com/car',build:{make:'Ford',model:'Mustang',engine:'5.0L V-8',cylinders:8}},false)!;
assert(matches(mc,filterSchema.parse({requiredTerms:['V8']})));
assert(!matches({...mc,engineText:'V6'},filterSchema.parse({requiredTerms:['V8']})));
const auto=normalizeAutoDev({vehicle:{make:'Audi',model:'S4',engine:{name:'3.0L supercharged V6'}},retailListing:{price:20000,used:true,vdp:'https://example.com/audi'}})!;
assert(matches(auto,filterSchema.parse({requiredTerms:['supercharged','V6']})));
assert.deepEqual(basic('find V8 cars',initialFilters).filters.requiredTerms,['v8']);
const broad=basic('find supercharged Audi',initialFilters);assert.equal(broad.filters.make,'Audi');assert.equal(broad.filters.model,'');assert.deepEqual(broad.filters.requiredTerms,['supercharged']);
assert(basic('find V6 or V8',initialFilters).question);
assert.deepEqual(localScoutRefinement('V8 only',initialFilters)?.filters.requiredTerms,['v8']);
assert.equal(localScoutRefinement('V8 under $30k',initialFilters),null);
console.log('PASS engine evidence, aliases, conservative factory inference, missing/conflicting specs, provider imports, parser and local refinements');

const {loadedScoutRefinement}=await import('../lib/local-scout-command');
assert.equal(loadedScoutRefinement('V8',{filters:initialFilters,searchedAt:null}),null,'first request must search, not filter an empty workspace');
assert(loadedScoutRefinement('V8',{filters:initialFilters,searchedAt:new Date().toISOString()}));
