import {sqliteD1} from './sqlite-d1';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {cachedInventory} from '../lib/inventory-cache';
import {initialFilters} from '../lib/domain';
const sql=new DatabaseSync(':memory:');sql.exec('CREATE TABLE workspaces(user_id TEXT PRIMARY KEY,payload TEXT,updated_at INTEGER)');
const db=sqliteD1(sql);
let calls=0,failed=false;
const search:typeof import('../lib/inventory').searchInventory=async()=>{calls++;return {listings:[],sources:[{name:'test',status:failed?'error':'searched',detail:failed?'HTTP 429':'Checked',count:0}],checkedAt:'2026-09-21T16:00:00Z',nextCursor:null}};
try{
 const first=await cachedInventory(db,initialFilters,{autodev:'secret-a'},undefined,search,1000000);
 const second=await cachedInventory(db,initialFilters,{autodev:'secret-a'},undefined,search,1000001);
 assert.equal(calls,1);assert.equal(first.checkedAt,second.checkedAt);assert(second.sources[0].detail.includes('Reused'));
 await cachedInventory(db,{...initialFilters,exteriorColor:'green'},{autodev:'secret-a'},undefined,search,1000002);assert.equal(calls,2,'changed requirements cannot reuse another query');
 await cachedInventory(db,initialFilters,{autodev:'secret-b'},undefined,search,1000003);assert.equal(calls,3,'different provider credentials stay isolated');
 await cachedInventory(db,initialFilters,{autodev:'secret-a'},undefined,search,1300001);assert.equal(calls,4,'expired data is refreshed');
 assert(!JSON.stringify(sql.prepare('SELECT * FROM workspaces').all()).includes('secret-'),'no plaintext credentials in stored keys or values');
 failed=true;
 await cachedInventory(db,initialFilters,{autodev:'failure'},undefined,search,1400000);
 await cachedInventory(db,initialFilters,{autodev:'failure'},undefined,search,1420000);assert.equal(calls,5);
 await cachedInventory(db,initialFilters,{autodev:'failure'},undefined,search,1430001);assert.equal(calls,5,'quota errors are not retried every 30 seconds');
 await cachedInventory(db,initialFilters,{autodev:'failure'},undefined,search,1700001);assert.equal(calls,6,'quota requests retry after five minutes');
 const broken={prepare(){throw Error('cache unavailable')}};
 await cachedInventory(broken,initialFilters,{},undefined,search,1500000);assert.equal(calls,7,'cache outage does not break live results');
 sql.prepare('INSERT INTO workspaces VALUES(?,?,?)').run('real-user','private-workspace',1);
 await cachedInventory(db,initialFilters,{},undefined,search,1600000);
 assert.equal((sql.prepare('SELECT payload FROM workspaces WHERE user_id=?').get('real-user') as {payload:string}).payload,'private-workspace','cleanup cannot delete user workspaces');
 const {inventoryStatus}=await import('../lib/inventory');
 let marketCalls=0,autoCalls=0;
 const providerSearch:typeof import('../lib/inventory').searchInventory=async(_filters,keys)=>{
  if(keys.marketcheck)marketCalls++;if(keys.autodev)autoCalls++;
  const sources=inventoryStatus(keys).map(source=>source.status==='ready'?{...source,status:(source.name==='Auto.dev · dealer inventory'?'searched':'error') as 'searched'|'error',detail:source.name==='Auto.dev · dealer inventory'?'Checked current inventory':'The provider reported a rate or quota limit. HTTP 429. Retry keeps your place.'}:source);
  return {listings:[],records:[],sources,checkedAt:'2026-09-29T12:00:00Z',nextCursor:keys.marketcheck?{dealer:50,private:null,auction:null,autodev:null,autotrader:null,retailers:null}:null};
 };
 const key={marketcheck:'quota-secret-credential',autodev:'healthy-secret-credential'};
 const position={dealer:50,private:null,auction:null,autodev:'1',autotrader:null,retailers:null};
 await cachedInventory(db,initialFilters,key,position,providerSearch,2000000);
 assert.equal(marketCalls,1);assert.equal(autoCalls,1);
 const cooled=await cachedInventory(db,{...initialFilters,model:'M5'},key,position,providerSearch,2000001);
 assert.equal(marketCalls,1,'new filters do not re-query the same exhausted connection');
 assert.equal(autoCalls,2,'the healthy other provider still runs for a new query');
 assert.equal(cooled.sources.find(source=>source.name==='MarketCheck · dealer inventory')?.status,'error');
 assert.match(cooled.sources.find(source=>source.name==='MarketCheck · dealer inventory')!.detail,/No new listings were checked/);
 assert.equal(cooled.nextCursor?.dealer,50,'paused sources retain their requested retry position');
 assert.equal(cooled.nextCursor?.private,null,'exhausted feeds are not reopened by cooldown');
 assert.equal(cooled.sources.find(source=>source.name==='MarketCheck · private sellers')?.status,'error','known provider cooldown remains visible on deferred slots');
 assert.equal(cooled.sources.find(source=>source.name==='MarketCheck · private sellers')?.hasMore,false);
 const onlyCooled=await cachedInventory(db,{...initialFilters,model:'M4'},{marketcheck:key.marketcheck},position,providerSearch,2000002);
 assert.equal(marketCalls,1,'no search call is needed when the only configured provider is cooling down');
 assert.deepEqual(onlyCooled.listings,[],'cooldown never fabricates matches');
 await cachedInventory(db,{...initialFilters,model:'M5'},{...key,marketcheck:'different-secret-key'},position,providerSearch,2000003);
 assert.equal(marketCalls,2,'another credential is not blocked by the first credential cooldown');
 await cachedInventory(db,{...initialFilters,model:'M3'},key,position,providerSearch,2299999);
 assert.equal(marketCalls,2);
 await cachedInventory(db,{...initialFilters,model:'M3'},key,position,providerSearch,2300000);
 assert.equal(marketCalls,3,'cooldown and skipped-query cache expire at the original five-minute deadline');
 let autoQuotaCalls=0;
 const autoQuota:typeof import('../lib/inventory').searchInventory=async()=>{autoQuotaCalls++;return {listings:[],sources:[{name:'Auto.dev · dealer inventory',status:'error',detail:'HTTP 429'}],checkedAt:'2026-09-29T12:00:00Z',nextCursor:{dealer:null,private:null,auction:null,autodev:'cursor:retry-token'}}};
 const oldCursor={dealer:null,private:null,auction:null,autodev:'cursor:retry-token'};
 await cachedInventory(db,initialFilters,{autodev:'auto-quota-secret'},oldCursor,autoQuota,2400000);
 const autoPaused=await cachedInventory(db,{...initialFilters,model:'M550i'},{autodev:'auto-quota-secret'},oldCursor,autoQuota,2400001);
 assert.equal(autoQuotaCalls,1,'Auto.dev cooldown also applies across filters');
 assert.deepEqual(autoPaused.nextCursor,oldCursor,'opaque retry position and absent optional cursor fields stay intact');
 const stored=JSON.stringify(sql.prepare('SELECT * FROM workspaces').all());
 for(const secret of [key.marketcheck,key.autodev,'different-secret-key','auto-quota-secret'])assert(!stored.includes(secret),'cooldown identifiers and payloads never persist credentials');
 assert(Number(sql.prepare("SELECT count(*) AS count FROM workspaces WHERE user_id GLOB '__inventory_cache__:*'").get()!.count)<=500,'response caches and cooldown markers share the existing cap');
 console.log('PASS: repeat reuse, exact filter/credential isolation, provider cooldowns, healthy-provider access, expiration and safe cleanup');
}finally{sql.close()}
