import zipData from '../lib/data/us-zips.json';
import assert from 'node:assert/strict';
import {filterSchema,initialFilters,matches} from '../lib/domain';
import {basic} from '../lib/basic-parser';
import {localLocationCommand,zipInText} from '../lib/location-command';
import {coordinates,locationMatches,locationLabel,milesBetween} from '../lib/location';
import {lookupZip,resolveZip} from '../lib/zip-location';
import {marketplaceInput,normalizeMarketplace} from '../lib/apify';
import {marketcheckUrl} from '../lib/marketcheck';
import {autoDevUrl} from '../lib/autodev';
const filters=await resolveZip(filterSchema.parse({make:'Audi',model:'R8',zip:'80487',radiusMiles:50,state:'TX'}));
assert.equal(filters.location?.city,'Steamboat Springs');assert.equal(filters.state,'');
assert.equal(locationLabel(filters),'50 miles from Steamboat Springs, CO 80487');
assert.equal(zipInText('under 60000 miles'),undefined);assert.equal(zipInText('under $80487'),undefined);
assert.equal(basic('find R8 near 02108',initialFilters).filters.zip,'02108');
assert.equal(basic('find R8 near 80487 within 50 miles',initialFilters).filters.radiusMiles,50);
assert.equal(basic('nationwide',filters).filters.zip,'');assert.equal(basic('in California',filters).filters.zip,'');
assert.equal(localLocationCommand('80487',filters)?.filters.model,'R8');
assert.equal(localLocationCommand('near 02108 within 25 miles',filters)?.filters.radiusMiles,25);
assert.equal(localLocationCommand('find a blue R8 near 80487',filters),null);
assert.equal(coordinates(null,null),null);assert.equal(coordinates('',''),null);
assert.equal(locationMatches({},filters),false);
assert.equal(locationMatches({coordinates:{latitude:40.63,longitude:-106.93}},filters),true);
assert.equal(locationMatches({coordinates:{latitude:39.74,longitude:-104.99}},filters),false);
assert.equal(locationMatches({locationQuery:{zip:'80487',radiusMiles:50}},filters),true);
assert.equal(locationMatches({locationQuery:{zip:'80487',radiusMiles:100}},filters),false);
assert.equal(locationMatches({locationQuery:{zip:'02108',radiusMiles:25}},filters),false);
assert.equal(locationMatches({},initialFilters),true);
assert.equal(milesBetween(filters.location!,filters.location!),0);
assert.equal(marketcheckUrl(filters,false).searchParams.get('zip'),'80487');
assert.equal(marketcheckUrl(filters,false).searchParams.get('radius'),'50');
assert.equal(autoDevUrl(filters).searchParams.get('distance'),'50');
assert.equal(autoDevUrl(filters).searchParams.has('retailListing.state'),false);
assert.deepEqual(marketplaceInput(filters).zipCodes,['80487']);assert.equal(marketplaceInput(filters).distanceMiles,50);
await assert.rejects(()=>lookupZip('00000'),/not found/);
assert.equal((await lookupZip('02108')).city,'Boston');
assert.equal((await resolveZip({...filters,zip:''})).location,null);
const row=normalizeMarketplace({url:'https://www.cars.com/vehicledetail/123/',brand:'Audi',model:'R8',name:'2018 Audi R8',vehicleModelDate:2018,offers:{price:90000,priceCurrency:'USD'},itemLocation:{address:{postalCode:'80487'},geo:{latitude:40.63,longitude:-106.93}}});
assert.ok(row);assert.equal(matches(row,filters),true);assert.equal(matches({...row,coordinates:null},filters),false);
console.log('ZIP parsing, lookup failures, radius enforcement and provider parameters passed.');

for(const [zip,p] of Object.entries(zipData)){assert.match(zip,/^\d{5}$/);assert.equal(p.length,4);assert.equal(typeof p[0],'string');assert.match(String(p[1]),/^[A-Z]{2}$/);assert.ok(coordinates(p[2],p[3]));}
