import assert from 'node:assert/strict';
import {localScoutCommand,localScoutRefinement} from '../lib/local-scout-command';
import {filterSchema} from '../lib/domain';
for(const text of ['Compare cars','Compare my selected cars','Compare the cheapest cars in my results',' compare my saved cars! '])assert.equal(localScoutCommand(text),'compare');
for(const text of ['Compare cars under $30k','Compare my selected cars but only AWD','Find cars','Compare a BMW to an Audi','Do not compare cars'])assert.equal(localScoutCommand(text),null);
console.log('PASS: local comparison shortcuts never swallow additional requirements');
const filters=filterSchema.parse({make:'Audi',model:'RS7',maxMiles:80000,exteriorColor:'green'});
assert.equal(localScoutRefinement('Lower mileage',filters)?.filters.maxMiles,70000);
assert.equal(localScoutRefinement('under 60k miles',filters)?.filters.maxMiles,60000);
assert.equal(localScoutRefinement('under 90k miles',filters),null,'broadening requires a fresh search');
assert.equal(localScoutRefinement('only AWD and red',filters),null,'do not drop additional requirements');
assert.equal(localScoutRefinement('Only AWD',filters)?.filters.exteriorColor,'green');
assert.equal(localScoutRefinement('Lower mileage',{...filters,maxMiles:null})?.action,'clarify');
console.log('PASS: loaded-result refinements preserve requirements and clarify missing mileage');

assert.equal(localScoutRefinement('Only show cars under 60000 miles',filters)?.filters.maxMiles,60000);
assert.equal(localScoutRefinement('show me ones under 50k miles',filters)?.filters.maxMiles,50000);
assert.equal(localScoutRefinement('under $40k',filters)?.filters.maxPrice,40000);
assert.equal(localScoutRefinement('only show green cars',{...filters,exteriorColor:''})?.filters.exteriorColor,'green');
assert.equal(localScoutRefinement('manual only',filters)?.filters.transmission,'manual');
assert.equal(localScoutRefinement('under $40k and under 20k miles',filters),null,'compound requests still need full interpretation');
assert.equal(localScoutRefinement('only red cars',filters),null,'changing an existing color requires fresh matching inventory');
