import assert from 'node:assert/strict';
import {initialFilters,filterSchema} from '../lib/domain';
import {basic} from '../lib/basic-parser';
import {localScoutRefinement} from '../lib/local-scout-command';
import {interpretSearch} from '../lib/search-assistant';
import {mileageRequest} from '../lib/mileage-range';
const current=filterSchema.parse({make:'BMW',model:'4 Series',trim:'M440i'});
const exact='find one that are with 30k to 50k miles thats around 35k';
const parsed=basic(exact,current);assert.equal(parsed.question,'');assert.equal(parsed.filters.minMiles,30000);assert.equal(parsed.filters.maxMiles,50000);assert.equal(parsed.filters.maxPrice,35000);
for(const text of ['between 30,000 and 50,000 miles','from 30k through 50k miles','30k–50k miles','30 to 50k miles','30–50k miles']){const range=basic(text,current);assert.equal(range.filters.minMiles,30000);assert.equal(range.filters.maxMiles,50000)}
assert.equal(basic('at least 30k miles',current).filters.minMiles,30000);
assert.equal(basic('at least 30k miles',current).filters.maxPrice,null);
assert.equal(mileageRequest('within 30 to 50 miles of ZIP 80202'),null);assert.equal(mileageRequest('$30k to $50k budget near 80202'),null);
assert.equal(mileageRequest('100 to 200 miles away'),null);
assert(mileageRequest('-5 to 10 miles')?.question);assert(mileageRequest('5 to -10 miles')?.question);
assert.equal(basic('around 80202',current).filters.maxPrice,null);assert.equal(basic('around 80202',current).filters.zip,'80202');
const reversed=basic('50k to 30k miles',current);assert.equal(reversed.action,'clarify');assert.deepEqual(reversed.filters,current);
const bounded=filterSchema.parse({...current,minMiles:30000,maxMiles:50000});
assert.equal(basic('make it blue',bounded).filters.minMiles,30000);
assert.equal(basic('find a Toyota Camry',bounded).filters.minMiles,null);assert.equal(basic('find Toyota',bounded).filters.minMiles,null);
const refined=localScoutRefinement('show cars with 30k to 50k miles',current,initialFilters);assert.equal(refined?.action,'refine');assert.equal(refined?.filters.minMiles,30000);assert.equal(refined?.filters.maxMiles,50000);
assert.equal(localScoutRefinement('at least 20k miles',bounded,bounded),null,'cannot broaden a loaded pool below its original minimum');
assert.equal(localScoutRefinement('50k to 30k miles',bounded)?.action,'clarify');
assert.equal(localScoutRefinement('lower mileage',{...bounded,maxMiles:35000})?.action,'clarify');
let calls=0;
const request:typeof fetch=async(_url,init)=>{calls++;const body=JSON.parse(String(init?.body));const schema=body.tools[0].function.parameters.properties.filters;assert(schema.required.includes('minMiles'));assert.deepEqual(schema.properties.minMiles.type,['number','null']);return Response.json({choices:[{message:{tool_calls:[{function:{name:'update_search',arguments:JSON.stringify({action:'search',question:'',filters:{...current,minMiles:null,maxMiles:50000,maxPrice:35000}})}}]}}]})};
const ai=await interpretSearch(exact,current,[],{apiKey:'fixture',request});assert.equal(ai.filters.minMiles,30000);assert.equal(ai.filters.maxMiles,50000);assert.equal(ai.filters.maxPrice,35000);
const followup=await interpretSearch('make it blue',bounded,[],{apiKey:'fixture',request});assert.equal(followup.filters.minMiles,30000,'model omission cannot drop active lower mileage on same-vehicle followup');
const cleared=await interpretSearch('no minimum mileage',bounded,[],{apiKey:'fixture',request});assert.equal(cleared.filters.minMiles,null,'explicitly clearing the minimum remains possible');
const before=calls;assert.equal((await interpretSearch('50k to 30k miles',current,[],{apiKey:'fixture',request})).action,'clarify');assert.equal(calls,before,'reversed ranges make no AI call');
const persisted=filterSchema.parse(JSON.parse(JSON.stringify(ai.filters)));assert.equal(localScoutRefinement('only awd',persisted,initialFilters)?.filters.minMiles,30000);
console.log('PASS: exact mileage bounds/budget, local followups, new-vehicle reset, range validation, strict AI schema and deterministic bounds');
