import assert from 'node:assert/strict';
import {previewAccess} from '../lib/preview-access';
const settings={PREVIEW_PASSWORD:'fixture-password',PREVIEW_COOKIE_SECRET:'fixture-cookie-secret'},origin='https://example.test',now=Date.now();
const request=(path='/',cookie?:string)=>new Request(origin+path,{headers:cookie?{cookie}:{}});
const submit=(password:string,extra={},requestOrigin=origin)=>new Request(origin+'/api/preview-access',{method:'POST',headers:{origin:requestOrigin},body:new URLSearchParams({password,...extra})});
const page=await previewAccess(request(),settings);assert.equal(page?.status,200);assert((await page!.text()).includes('Private preview'));
for(const path of ['/api/workspace','/api/connections','/api/vehicles','/api/photos','/api/marketplaces','/api/status'])assert.equal((await previewAccess(request(path),settings))?.status,401);
assert.equal((await previewAccess(submit('wrong'),settings))?.status,401);
assert.equal((await previewAccess(submit(settings.PREVIEW_PASSWORD,{},'https://attacker.test'),settings))?.status,403);
assert.equal((await previewAccess(submit(settings.PREVIEW_PASSWORD),settings,async()=>false))?.status,429);
assert.equal((await previewAccess(request(),{PREVIEW_PASSWORD:'fixture-password'}))?.status,503);
const accepted=await previewAccess(submit(settings.PREVIEW_PASSWORD,{returnTo:'/help'}),settings,undefined,now);assert.equal(accepted?.status,303);assert.equal(accepted?.headers.get('location'),'/help');
const cookie=accepted!.headers.get('set-cookie')!;for(const flag of ['HttpOnly','Secure','SameSite=Lax','Path=/'])assert(cookie.includes(flag));assert(!cookie.includes(settings.PREVIEW_PASSWORD));
assert.equal(await previewAccess(request('/api/workspace',cookie.split(';')[0]),settings,undefined,now),null);
assert.equal((await previewAccess(request('/',cookie.replace(/.$/,'x').split(';')[0].replace(/.$/,'x')),settings))?.status,200,'tampered cookie shows gate');
assert.equal((await previewAccess(request('/',cookie.split(';')[0]),settings,undefined,now+86400001))?.status,200,'expired cookie shows gate');
assert.equal((await previewAccess(new Request('https://other.test/',{headers:{cookie:cookie.split(';')[0]}}),settings))?.status,200,'cookie is host-bound');
assert.equal((await previewAccess(request('/',cookie.split(';')[0]),{...settings,PREVIEW_PASSWORD:'changed'}))?.status,200,'password rotation invalidates cookies');
assert.equal((await previewAccess(submit(settings.PREVIEW_PASSWORD,{returnTo:'//attacker.test'}),settings))?.headers.get('location'),'/');
assert.equal((await previewAccess(submit(settings.PREVIEW_PASSWORD,{returnTo:'/api/workspace'}),settings))?.headers.get('location'),'/');
assert.equal(await previewAccess(request(),{}),null);
assert.equal(await previewAccess(request('/api/jobs/alerts'),settings),null);
assert.equal(await previewAccess(request('/api/alerts/unsubscribe'),settings),null);
console.log('PASS: preview gate blocks pages/APIs, verifies password, rejects forged/expired cookies and cross-origin submissions; preserves existing account and scheduler authentication');
