import assert from 'node:assert/strict';
import {healthyCursor,preserveDeferredCursor,mergeSearch,mergeSources} from '../lib/search-session';
import {encodeWorkspace,decodeWorkspace} from '../lib/workspace-codec';
import {initialFilters,filterSchema,firstCursor,rank} from '../lib/domain';
import {normalizeMarketcheck,marketcheckUrl} from '../lib/marketcheck';
import {basic} from '../lib/basic-parser';
import {inventoryStatus} from '../lib/inventory';
const car=(i:number)=>normalizeMarketcheck({id:String(i),vin:String(i).padStart(17,'0'),price:45000+i,vdp_url:`https://example.test/${i}`,base_ext_color:'Green',exterior_color:'Isle of Man Green Metallic',build:{make:'BMW',model:'M4',year:2023,trim:'Competition'},miles:12000},false)!;
const f=filterSchema.parse({make:'BMW',model:'M4',exteriorColor:'green'});
const merged=mergeSearch([car(1),car(2)],[car(2),car(3)],f);
const mislabeled={...car(70),price:7500,year:2010,miles:150000,evidenceText:'Savings $7,500. Full asking price $25,000.'};
assert.equal(mergeSearch([], [mislabeled], {...f,maxPrice:10000}).length,0,'marketplace-style imports are reviewed before the first budget match');
assert.equal(mergeSearch([mislabeled], [], {...f,maxPrice:10000}).length,0,'previously collected bad amounts cannot survive a follow-up');
assert(mergeSearch([], [mislabeled], f)[0].priceWarning,'unbudgeted browsing withholds the mislabeled amount');
const expired={...car(71),priceReview:{status:'matched' as const,checkedAt:new Date(Date.now()-25*3600000).toISOString(),reportedPrice:45071,sourcePrice:45071,note:'Previously checked'}};
assert.equal(mergeSearch([], [expired], {...f,maxPrice:50000}).length,0,'cached result checks must still be fresh when consumed');
assert.equal(merged.length,3,'later pages append and deduplicate instead of replacing results');
assert.equal(mergeSearch(merged,[{...car(2),price:42000}],f).find(r=>r.id===car(2).id)?.price,42000);
assert.equal(mergeSearch(merged,[{...car(4),exteriorColor:'Blue',baseExteriorColor:'Blue'}],f).length,3);
assert.equal(healthyCursor(firstCursor(),[{name:'MarketCheck · dealer inventory',status:'error',detail:'quota'}])?.dealer,null,'failed sources are not repeatedly retried automatically');
assert.equal(healthyCursor({dealer:50,private:null,auction:null,autodev:null},[{name:'MarketCheck · dealer inventory',status:'error',detail:'quota'}]),null);
const reordered=inventoryStatus({marketcheck:'fixture',autodev:'fixture'}).reverse();
for(const source of reordered)if(['Auto.dev · dealer inventory','MarketCheck · private sellers','CarGurus'].includes(source.name))source.status='error';
const healthy=healthyCursor(firstCursor(),reordered)!;
assert.equal(healthy.autodev,null);assert.equal(healthy.private,null);
const partial={dealer:50,private:null,auction:null,autodev:'2',autotrader:null,retailers:null};
const limitedSources=inventoryStatus({marketcheck:'fixture',autodev:'fixture'});
limitedSources.find(source=>source.name==='MarketCheck · dealer inventory')!.status='error';
const deferred=preserveDeferredCursor({...partial,dealer:null,autodev:'3'},partial,limitedSources)!;
assert.equal(deferred.dealer,50,'background progress preserves the failed dealer page for manual retry');
assert.equal(deferred.autodev,'3','healthy source advances normally');
assert.equal(healthyCursor(deferred,limitedSources)?.dealer,null,'preserving a retry does not automatically repeat failed requests');
const onlyRetry=preserveDeferredCursor(null,deferred,limitedSources)!;
assert.equal(onlyRetry.dealer,50);assert.equal(onlyRetry.autodev,null);
assert.equal(healthyCursor(onlyRetry,limitedSources),null,'automatic gathering ends when only blocked feeds remain');
assert.equal(preserveDeferredCursor(null,partial,[]),null,'exhausted healthy feeds are not resurrected');
assert.equal(healthy.dealer,firstCursor().dealer,'unrelated marketplace failures cannot stop healthy dealer pagination');
assert.equal(healthy.auction,firstCursor().auction);assert.equal(healthy.autotrader,firstCursor().autotrader);assert.equal(healthy.retailers,firstCursor().retailers);
const marketplaceEvidence=[{name:'CarGurus',status:'searched' as const,detail:'17 marketplace listings returned',count:17,inspected:17},{name:'Carvana',status:'searched' as const,detail:'Independent Apify import',count:2,inspected:2},{name:'Cars.com',status:'error' as const,detail:'No usable listings returned'}];
const nextDealerPage=inventoryStatus({marketcheck:'fixture'});
Object.assign(nextDealerPage[0],{status:'searched',count:5,inspected:5});
const afterDealerPage=mergeSources(marketplaceEvidence,nextDealerPage);
for(const source of marketplaceEvidence)assert.deepEqual(afterDealerPage.find(row=>row.name===source.name),source,'dealer placeholders must preserve independent marketplace evidence');
assert.equal(afterDealerPage.find(source=>source.name==='MarketCheck · dealer inventory')?.count,5);
assert.deepEqual(mergeSources(marketplaceEvidence,[{name:'MarketCheck · dealer inventory',status:'searched',detail:'next page',inspected:5}]).filter(source=>source.name!=='MarketCheck · dealer inventory'),marketplaceEvidence,'sources omitted from a page remain visible');
const sources=mergeSources([{name:'dealer',status:'searched',detail:'first',inspected:50,total:120}],[{name:'dealer',status:'searched',detail:'next',inspected:50,total:120}]);
assert.equal(sources[0].inspected,100);assert.equal(sources[0].total,120);
const fresh=basic('find a green M4',filterSchema.parse({make:'Ford',model:'F-150',bodyType:'pickup',cabStyle:'crew',drivetrain:'4wd',maxPrice:35000}));
assert.equal(fresh.filters.model,'M4');assert.equal(fresh.filters.cabStyle,'');assert.equal(fresh.filters.bodyType,'');assert.equal(fresh.filters.maxPrice,null);
assert.equal(marketcheckUrl({...f,exteriorColor:'Isle of Man Green'},false).searchParams.get('exterior_color'),'Isle of Man Green');
assert.equal(mergeSearch([], [car(1)], {...f,exteriorColor:'Isle of Man Green'}).length,1);
assert.equal(filterSchema.parse({make:'Morgan',model:'Plus Six',trim:'Bespoke edition'}).trim,'Bespoke edition','manual entries are not restricted to the suggestion catalogue');
let repeatedlyRanked=[car(1)];for(let i=0;i<20;i++)repeatedlyRanked=rank(repeatedlyRanked,repeatedlyRanked,initialFilters,100);
assert(repeatedlyRanked[0].concerns.length<10,'reading accumulated results does not endlessly duplicate concerns');
const large={listings:Array.from({length:3000},(_,i)=>car(i)),filters:f};
const packed=await encodeWorkspace(large);assert(packed.startsWith('gzip:'));assert(packed.length<1500000);assert.deepEqual(await decodeWorkspace(packed),large);
assert.deepEqual(await decodeWorkspace(JSON.stringify({listings:[]})),{listings:[]},'existing workspaces remain readable');
console.log('PASS: accumulation, duplicate updates, hard filters, failed-source stopping, fresh M4 search, freeform vehicles, exact paint and 3,000-car storage');

const {collectWorkspace,refineWorkspace}=await import('../lib/search-session');
const {blankWorkspace}=await import('../lib/domain');
const {localScoutRefinement}=await import('../lib/local-scout-command');
const pool=blankWorkspace();pool.filters=filterSchema.parse({make:'BMW',model:'M4'});
const green={...car(100),exteriorColor:'Green',baseExteriorColor:'Green',miles:20000};
const blue={...car(101),exteriorColor:'Blue',baseExteriorColor:'Blue',miles:70000};
collectWorkspace(pool,[green,blue],true);
refineWorkspace(pool,{...pool.filters,exteriorColor:'green'});
assert.equal(pool.listings.length,1);assert.equal(pool.collected!.length,2);
const blueRequest=localScoutRefinement('blue cars',pool.filters,pool.poolFilters!);assert(blueRequest);refineWorkspace(pool,blueRequest.filters);assert.equal(pool.listings[0].id,blue.id);
const restore=localScoutRefinement('show all collected cars',pool.filters,pool.poolFilters!);assert(restore);refineWorkspace(pool,restore.filters);assert.equal(pool.listings.length,2);
refineWorkspace(pool,{...pool.filters,maxMiles:30000});
const widen=localScoutRefinement('under 80k miles',pool.filters,pool.poolFilters!);assert(widen);refineWorkspace(pool,widen.filters);assert.equal(pool.listings.length,2);
assert.equal(localScoutRefinement('under 90k miles',filterSchema.parse({maxMiles:60000}),filterSchema.parse({maxMiles:80000})),null,'cannot pretend pool covers inventory beyond its original query');
collectWorkspace(pool,[{...blue,price:42000}]);assert.equal(pool.collected!.find(x=>x.id===blue.id)?.price,42000);
const persisted=await decodeWorkspace(await encodeWorkspace(pool));assert.equal(persisted.collected.length,2);
pool.filters=filterSchema.parse({make:'Audi'});collectWorkspace(pool,[],true);assert.equal(pool.collected!.length,0);assert.equal(pool.poolFilters!.make,'Audi','fresh searches reset pool scope');
console.log('PASS: reversible local refinements, price updates, pool bounds, persistence and fresh-search isolation');

// Retain alternate full records through VIN deduplication and subsequent refreshes.
const duplicatePool=blankWorkspace();duplicatePool.filters=f;
const a={...car(200),price:30000,checkedAt:'2026-09-28T00:00:00Z',photo:'https://images.example/a.jpg',photos:['https://images.example/a.jpg']};
const b={...a,id:'source-b',url:'https://other.example/car/200',source:'other.example',price:31000,photo:'https://images.example/b.jpg',photos:['https://images.example/b.jpg'],photosSourceUrl:'https://other.example/car/200'};
collectWorkspace(duplicatePool,[a,b],true);
assert.equal(duplicatePool.collected!.length,2,'complete source records survive collecting one VIN');
assert.equal(duplicatePool.listings.length,1);
collectWorkspace(duplicatePool,[{...b,price:32000,checkedAt:'2026-09-29T00:00:00Z'}]);
assert.equal(duplicatePool.listings[0].offers!.find(offer=>offer.url===b.url)?.price,32000,'secondary source refresh replaces its stale offer');
collectWorkspace(duplicatePool,[{...a,price:34000,checkedAt:'2026-09-29T00:00:00Z'}]);
assert.equal(duplicatePool.listings[0].id,b.id,'a primary price increase can select the retained cheaper alternate');
assert.equal(duplicatePool.listings[0].price,32000);
assert.deepEqual(duplicatePool.listings[0].photos,b.photos,'alternate selection uses that source gallery exclusively');
assert.equal(duplicatePool.listings[0].photosSourceUrl,b.url);
assert.equal(duplicatePool.listings[0].offers!.find(offer=>offer.url===a.url)?.price,34000);
collectWorkspace(duplicatePool,[{...b,price:35000,checkedAt:'2026-09-29T00:00:00Z'}]);
assert.equal(duplicatePool.listings[0].id,a.id,'equal timestamp incoming refresh takes precedence');
assert.deepEqual(duplicatePool.listings[0].photos,a.photos);
collectWorkspace(duplicatePool,[b]);
assert.equal(duplicatePool.listings[0].offers!.find(offer=>offer.url===b.url)?.price,35000,'older source snapshots cannot restore stale low prices');
const duplicateRoundTrip=await decodeWorkspace(await encodeWorkspace(duplicatePool));
assert.equal(duplicateRoundTrip.collected.length,2,'complete alternate records persist');

const legacy=mergeSearch([], [a,b],f);
const legacyUpdated=mergeSearch(legacy,[{...a,price:34000,checkedAt:'2026-09-29T00:00:00Z'}],f);
assert.deepEqual(legacyUpdated[0].offers!.map(offer=>offer.url),[a.url],'legacy primary replacement cannot pretend its lost alternate record is still retained');
assert.deepEqual(legacyUpdated[0].photos,a.photos);
const legacySecondaryUpdate=mergeSearch(legacy,[{...b,price:50000,checkedAt:'2026-09-29T00:00:00Z'}],{...f,maxPrice:40000});
assert(!legacySecondaryUpdate[0].offers!.some(offer=>offer.url===b.url),'a refreshed out-of-budget offer cannot survive inside an older composite');
const capped=blankWorkspace();capped.filters=f;
collectWorkspace(capped,Array.from({length:3002},(_,index)=>({...a,id:'offer-'+index,url:`https://seller.example/${index}`})),true);
assert.equal(capped.collected!.length,3000,'raw records remain bounded by the existing storage cap');
assert.equal(capped.listings.length,1,'the raw-record cap does not disable vehicle deduplication');
