import {sqliteD1} from './sqlite-d1';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {budgetedAiRequest,SHARED_AI_MODEL} from '../lib/shared-ai-budget';
import {resolveProviderCredential} from '../lib/shared-marketplace';
import {interpretSearch} from '../lib/search-assistant';
import {initialFilters} from '../lib/domain';
const stored=async(id:string,p:string)=>id==='owner'&&p==='openai'?'test-private-key':undefined;
assert.equal(await resolveProviderCredential('guest','openai',{SHARED_FREE_APIFY_OWNER_ID:'owner'},stored),undefined);
const key=await resolveProviderCredential('guest','openai',{SHARED_OPENAI_OWNER_ID:'owner'},stored);
assert.equal(key,'test-private-key');
assert.equal(await resolveProviderCredential('guest','autodev',{SHARED_OPENAI_OWNER_ID:'owner'},stored),undefined);
assert.equal(await resolveProviderCredential('guest','openai',{SHARED_OPENAI_OWNER_ID:'missing'},stored),undefined);
const sqlite=new DatabaseSync(':memory:');
sqlite.exec('CREATE TABLE usage(user_id TEXT,day TEXT,count INTEGER,PRIMARY KEY(user_id,day))');
const database=sqliteD1(sqlite);
let calls=0,day=0;
const request:typeof fetch=async(_url,init)=>{calls++;assert.equal(init?.redirect,'manual');assert.equal(new Headers(init?.headers).get('Authorization'),'Bearer test-private-key');return Response.json({choices:[{message:{tool_calls:[{function:{name:'update_search',arguments:JSON.stringify({filters:{...initialFilters,make:'Audi',model:'RS7'},action:'search',question:''})}}]}}]})};
const guarded=budgetedAiRequest(database,request,()=>day);
const run=()=>interpretSearch('Find an Audi RS7',initialFilters,[],{apiKey:key,model:SHARED_AI_MODEL,request:guarded});
const results=await Promise.allSettled(Array.from({length:55},run));
assert.equal(results.filter(r=>r.status==='fulfilled').length,50);
assert.equal(calls,50);
assert.equal((results[0] as PromiseFulfilledResult<Awaited<ReturnType<typeof run>>>).value.filters.model,'RS7');
await assert.rejects(run,/shared AI allowance/);
day=86400000;await run();assert.equal(calls,51);
await assert.rejects(()=>guarded('https://api.openai.com/v1/chat/completions',{method:'POST',body:'x'.repeat(24001)}),/too long/);
await assert.rejects(()=>guarded('https://api.openai.com/v1/chat/completions',{method:'POST',body:JSON.stringify({model:'expensive-model',max_tokens:1600,messages:[]})}),/safeguards/);
assert.equal(calls,51);
const fail=budgetedAiRequest(database,async()=>{throw Error('timeout')},()=>2*86400000);
await assert.rejects(()=>interpretSearch('Audi RS7',initialFilters,[],{apiKey:key,model:SHARED_AI_MODEL,request:fail}),/timeout/);
assert.equal(sqlite.prepare('SELECT count FROM usage WHERE day=?').get('1970-01-03')?.count,1,'Ambiguous failures retain reservation');
sqlite.close();console.log('PASS: visitor AI sponsorship, request restrictions, concurrent shared cap, UTC reset and timeout reservations');
