import assert from 'node:assert/strict';
import {blankWorkspace,type Listing} from '../lib/domain';
import {restoreComparisons,toggleComparison,workspaceCars,collectedCarCount} from '../lib/shortlist';
const car=(id:string)=>({id,title:id,price:30000} as Listing);
const w=blankWorkspace();w.listings=[car('a'),car('b'),car('c'),car('d')];
toggleComparison(w,w.listings[0]);
assert.equal(w.saved.length,0,'comparing does not silently save a favorite');
w.saved=[w.listings[0]];w.saved=[];w.listings=[];
restoreComparisons(w);
assert.deepEqual(w.compare,['a'],'unsaving and starting another search preserve comparison');
assert.equal(workspaceCars(w)[0].id,'a','car details remain accessible');
w.saved=[car('a')];toggleComparison(w,car('a'));
assert.equal(w.compare.length,0);assert.equal(w.saved.length,1,'removing a comparison preserves saved car');
for(const id of ['a','b','c'])toggleComparison(w,car(id));
assert.throws(()=>toggleComparison(w,car('d')),/three cars/);
const old=blankWorkspace();old.saved=[car('legacy')];old.compare=['missing','legacy','legacy'];
restoreComparisons(old);assert.deepEqual(old.compare,['legacy']);assert.equal(old.comparisonCars?.[0].id,'legacy','old workspaces migrate without losing comparison');
old.listings=[{...car('legacy'),price:28000}];restoreComparisons(old);
assert.equal(old.comparisonCars?.[0].price,28000,'fresh results update retained comparison');
old.filters.shippingAllowance=1000;assert.equal(workspaceCars(old)[0].total,29000,'retained cars use the current shipping reserve, not a stale subtotal');
console.log('PASS: independent saved/compared lists, retention, migration, limits and updated car details');

const firstOffer={...car('offer-a'),vin:'12345678901234567',url:'https://seller-a.example/car'};
const secondOffer={...firstOffer,id:'offer-b',url:'https://seller-b.example/car'};
assert.equal(collectedCarCount({listings:[firstOffer],collected:[firstOffer,secondOffer]}),1,'two source offers count as one collected car');
assert.equal(collectedCarCount({listings:[firstOffer],collected:[firstOffer,secondOffer,{...secondOffer,id:'another',vin:'76543210987654321'}]}),2,'hidden second vehicle still enables restore collection');
assert.equal(collectedCarCount({listings:[firstOffer]}),1,'legacy collections count visible cars');
