import assert from 'node:assert/strict';
import {photoUrls,fetchVehiclePhotos} from '../lib/vehicle-photos';
import {normalizeMarketplace} from '../lib/apify';
import {normalizeMarketcheck} from '../lib/marketcheck';
import {deduplicate} from '../lib/domain';
const first='https://images.example/first.jpg',second='https://images.example/second.jpg';
assert.deepEqual(photoUrls(first,[first,{url:second},{contentUrl:'javascript:alert(1)'},'https://secret:password@images.example/a','https://images.example/a?api_key=secret']),[first,second]);
assert.equal(photoUrls(Array.from({length:100},(_,i)=>`https://images.example/${i}.jpg`)).length,60);
const car=normalizeMarketcheck({id:'1',vdp_url:'https://dealer.example/car/1',price:50000,build:{year:2010,make:'Audi',model:'R8'},media:{photo_links:[first,second]}},false)!;
assert.deepEqual(car.photos,[first,second]);
assert.deepEqual(deduplicate([car,{...car,photos:['https://images.example/third.jpg']}])[0].photos,[first,second,'https://images.example/third.jpg']);
const marketplace=normalizeMarketplace({url:'https://cars.com/vehicledetail/1/',brand:'Audi',model:'R8',offers:{price:50000,priceCurrency:'USD'},image:[{url:first},{url:second}]});
assert.equal(marketplace?.photo,first);assert.deepEqual(marketplace?.photos,[first,second]);
let calls=0;
const fetcher:typeof fetch=async(url,init)=>{calls++;assert.equal(init?.redirect,'manual');assert.equal(String(url),'https://api.auto.dev/photos/WP0AA2990WS321225');assert.equal(new Headers(init?.headers).get('Authorization'),'Bearer test');return Response.json({data:{retail:[first,second]}})};
assert.deepEqual(await fetchVehiclePhotos('WP0AA2990WS321225','test',fetcher),[first,second]);
await assert.rejects(()=>fetchVehiclePhotos('../bad','test',fetcher),/valid VIN/);assert.equal(calls,1);
assert.deepEqual(await fetchVehiclePhotos('WP0AA2990WS321225','test',async()=>new Response('',{status:404})),[]);
await assert.rejects(()=>fetchVehiclePhotos('WP0AA2990WS321225','test',async()=>new Response('',{status:429})),/allowance/);
console.log('PASS: image normalization, gallery retention, safe VIN requests and provider failure handling');
