import {InfoPage} from '@/components/info-page';
import {SupportContact} from '@/components/support-contact';
export const dynamic='force-dynamic';
export default function Privacy(){return <InfoPage title="Your information on MotorScout." intro="Current data practices for the early-access version. Updated September 21, 2026.">
<section><h2>What the app stores</h2><p>MotorScout uses your authenticated account identifier to keep your search workspace separate. It stores search requirements, collected listings, recent conversation messages, saved and compared cars, saved searches, notifications and usage counters. If you enable email alerts after email is activated, the app uses your authenticated account email.</p><p>If you choose to connect a provider account, its API credential is encrypted in storage. Credentials stay on the server and are used with that provider. Do not put financial details, passwords or other sensitive information into Scout chat.</p></section>
<section><h2>Where requests go</h2><p>Search requirements are sent to the inventory services configured for your account, such as Auto.dev, MarketCheck and Apify. When OpenAI is configured, Scout sends your request, current search requirements and recent conversation context to OpenAI to interpret it. ZIP locations are resolved within MotorScout using bundled GeoNames data. Your chosen ZIP and radius are included in inventory search requests. These providers process requests under their own policies.</p><p>The website runs on OpenAI Sites and Cloudflare infrastructure. If email delivery is activated, Resend receives the recipient address and notification content. Opening a seller link takes you to a separate website with its own policies. Listing photos may load from external hosts, which receive ordinary browser requests.</p></section>
<section><h2>How information is used</h2><p>The app uses this information to find cars, preserve your choices, deliver notifications you request, enforce usage limits and troubleshoot failures. MotorScout does not send your contact details to dealerships merely because you search or save a car. Any contact you make through a seller's website is handled there.</p></section>
<section><h2>Your controls and retention</h2><p>Remove saved cars and comparisons in their respective tabs. Reset chat clears the current stored conversation, but keeps your cars and filters. Remove a saved search to remove its associated in-app notifications and email preference. Disconnect a provider in Sources to remove its stored credential from MotorScout; this does not close your account with that provider.</p><p>Workspace data is retained while it remains saved in the app; automatic account-wide expiry is not currently implemented. Recent inventory responses may be cached briefly. Operational logs, provider records and usage records are separate from visible workspace controls. Those controls do not promise deletion from third-party systems or backups.</p></section>
<section><h2>Privacy questions</h2><SupportContact/><p>Public launch remains pending a working private support contact and completion of the launch access checks.</p></section>
</InfoPage>}
