import {InfoPage} from '@/components/info-page';
import {SupportContact} from '@/components/support-contact';
export const dynamic='force-dynamic';
export default function Terms(){return <InfoPage title="Using MotorScout." intro="Early-access service terms. Updated September 21, 2026.">
<section><h2>What MotorScout provides</h2><p>MotorScout is a vehicle discovery and comparison tool. It does not sell the listed vehicles, hold deposits, arrange financing or complete purchases. A listing is information from a third-party source, not an offer from MotorScout.</p></section>
<section><h2>Check before you buy</h2><p>Verify the vehicle&apos;s availability, full cash price, fees, condition, title, history and equipment directly with its seller. Listings can change or contain mistakes. AI interpretation and price comparisons can be incomplete or wrong. Comparisons are based on asking prices, not certified appraisals or completed transactions.</p></section>
<section><h2>Coverage and availability</h2><p>Access is limited to the inventory and providers currently available to your account. MotorScout does not promise every vehicle, nationwide completeness, a minimum number of exact matches, uninterrupted access or notification delivery. Source quotas and outages may interrupt searches. Features marked unavailable or awaiting activation are not active services.</p></section>
<section><h2>Your account and connected services</h2><p>Use only accounts and provider credentials you are authorized to use. Follow the applicable provider terms. Provider usage may have its own limits or charges; MotorScout&apos;s search allowance does not increase those limits. Do not bypass access controls, extract other users&apos; information, submit malicious content or misuse the service.</p></section>
<section><h2>Listings and third-party content</h2><p>Listing text, photos and marks belong to their respective owners. Source names identify where records came from and do not imply a partnership or endorsement. Seller and provider policies apply when you use their services.</p></section>
<section><h2>Changes and support</h2><p>This is an early-access product. Features and access may change as testing continues. Material changes to these pages will carry an updated date.</p><SupportContact/></section>
</InfoPage>}
