import {applyLocationText} from './location-command';
import {filterSchema,type Filters,type Message} from './domain';
import {detailProperties} from './vehicle-requirements';
import {basic} from './basic-parser';
const properties={...detailProperties,make:{type:'string'},model:{type:'string'},trim:{type:'string'},maxPrice:{type:['number','null']},maxMiles:{type:['number','null']},minYear:{type:['number','null']},state:{type:'string'},zip:{type:'string'},radiusMiles:{type:'number'},seller:{type:'string',enum:['any','private','dealer']},awd:{type:'boolean'},cleanTitle:{type:'boolean'},shippingAllowance:{type:'number'},limit:{type:'number'}};
const instructions=`You translate a user's used-car shopping request into exact inventory requirements. Always call update_search. Never return the user's words as a clarification or merely paraphrase a search: action search actually executes it.
For a U.S. ZIP location use zip as a five-digit string (preserve leading zeros), state empty, and radiusMiles for distance from the ZIP center. Use 100 miles unless the user specifies another radius. Keep ZIP/radius on follow-ups; clear zip when the user changes to a state or nationwide. Never confuse ZIP codes with budgets or vehicle mileage.
Support exterior color, body type (truck=pickup), fuel, transmission, drivetrain (4x4=four-wheel-drive=4wd, distinct from awd), cab style, and each listed equipment feature, plus make/model/trim, budget, mileage, oldest year, state, seller, clean title, and shipping reserve.
Use exteriorColor for exterior paint only. A green truck with black leather has exteriorColor green, bodyType pickup, features leather seats and requiredTerms ["black leather"]. Additional terms need explicit seller evidence; never infer interior color from paint. Never silently omit any must-have. Features and requiredTerms are ALL required, not alternatives. Ask a specific question if an OR choice cannot be represented.
Carry forward all active requirements on follow-ups such as 'only diesel', 'make it blue', or 'under 60k miles'. A clearly new make/model request such as 'find a green M4' after trucks starts a fresh search: clear previous body type, cab, drivetrain, features, color, budget, mileage, year, seller and location unless the user says to keep them or states them again. Follow-ups about the SAME car keep active requirements. Never carry a truck's crew cab or 4WD requirement into a sports-car search. Set awd false when explicitly requesting 4wd/fwd/rwd, and use drivetrain. If no change was requested, keep the existing value. Do not infer clean title, location, or features from appearance.
Any make, model and trim may be requested; there is no preset catalogue restriction. Distinguish models from trims: Audi S3, S4, S5, S6, S7, S8, SQ5, SQ7, SQ8, RS3, RS4, RS5, RS6, RS7, RS Q8, TT, TTS, TT RS, R8 and e-tron families are models, not trims of A3/A4/A5/Q5. For Audi Premium, Premium Plus, Prestige, Progressiv, Technik, S line, Competition or performance requests preserve the exact requested designation in trim; do not invent availability, interchange tiers, or apply one model’s trims to every Audi. If only a make and trim is specified, leave model empty to search across that make. Trims vary with model, year and market. Canonical spelling is resolved against connected inventory after this call. Map M4 to make BMW, model M4, and leave trim empty unless specified. Preserve exact paint names (Isle of Man Green) when requested; use a base color for generic green. Map BMW M340i to make BMW, model 3 Series, trim M340i. Budget includes disclosed fees and user shipping allowance. Never invent a shipping quote. Lower mileage without a number: subtract 10000 from an existing maximum, floor 0; ask for a number if none. No unstated defaults for budget/mileage/location. Questions about best value/comparison use action compare; saves use save; alerts use alert.
question must be empty for executable searches. Use action clarify only for genuinely missing information or requirements whose meaning needs clarification. For custom equipment, modifications, packages or interior specifications outside named filters, put concise exact seller phrases in requiredTerms, such as "overland", "black leather" or "long bed". These phrases are mandatory and will be checked against seller evidence. Clear requiredTerms on a new vehicle search unless the user keeps them. For numeric performance guarantees or accident-free history without structured evidence, clarify instead. Say which requirement cannot currently be verified and ask whether to search without it. Never run a search that silently discards it. Do not ask users to repeat supported requirements.
Return the complete filter object, not a patch. All claims about listings come from inventory, never from you.`;
export async function interpretSearch(text:string,filters:Filters,messages:Message[],options:{apiKey?:string;model?:string;request?:typeof fetch}={}){
 const current=filterSchema.parse(filters);
 // Relative mileage needs an existing limit or an explicit amount; model output is not evidence of user intent.
 const relativeMileage=/\b(?:lower|less|fewer|reduce|decrease)\s+(?:the\s+)?(?:mileage|miles)\b|\bmileage\s+(?:lower|less)\b/i.test(text);
 const explicitMileage=/\b\d[\d,.]*\s*k?\s*(?:miles|mi\b)|\b(?:mileage|miles)\s*(?:(?:under|below|to|of|at|max(?:imum)?|limit|is)\s*)*[:=]?\s*\d/i.test(text);
 if(relativeMileage&&current.maxMiles===null&&!explicitMileage)return {filters:current,question:'What maximum mileage would you like? Your current cars and requirements will stay unchanged until you choose a limit.',action:'clarify',mode:options.apiKey?'AI':'Basic filter parser · AI not connected'};

 if(!options.apiKey)return basic(text,current);
 const response=await (options.request??fetch)('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${options.apiKey}`,'Content-Type':'application/json'},signal:AbortSignal.timeout(25000),body:JSON.stringify({model:options.model||'gpt-4.1-mini',max_tokens:1600,temperature:0,store:false,parallel_tool_calls:false,
 messages:[{role:'system',content:instructions},{role:'system',content:'Current filters: '+JSON.stringify(current)},...messages.slice(-6).map(m=>({role:m.role,content:m.text})),{role:'user',content:text}],
 tools:[{type:'function',function:{name:'update_search',description:'Execute an exact used-car search or ask one necessary clarification.',strict:true,parameters:{type:'object',properties:{filters:{type:'object',properties,required:Object.keys(properties),additionalProperties:false},question:{type:'string'},action:{type:'string',enum:['search','clarify','compare','save','alert']}},required:['filters','question','action'],additionalProperties:false}}}],tool_choice:{type:'function',function:{name:'update_search'}}})});
 if(!response.ok)throw Error(`AI service unavailable (${response.status}). Your filters are unchanged; try again or use the search controls.`);
 const data:any=await response.json();const call=data.choices?.[0]?.message?.tool_calls?.[0];
 if(call?.function?.name!=='update_search')throw Error('The assistant did not provide executable search filters. Please retry.');
 const args=JSON.parse(call.function.arguments);
 if(!['search','clarify','compare','save','alert'].includes(args.action))throw Error('The assistant returned an invalid action. Your filters are unchanged.');
 const parsed=filterSchema.parse(applyLocationText(text,args.filters));
 const question=args.action==='clarify'?String(args.question??'').trim().slice(0,600):'';
 if(args.action==='clarify'&&(!question||question.toLowerCase()===text.trim().toLowerCase()))return basic(text,current);
 return {filters:parsed,question,action:args.action,mode:'AI'};
}
