import {record} from '@/lib/unknown-data';
import {verifyFreeAccount,MarketplaceError} from '@/lib/apify';
import {identity,boundedJson,limitUsage,config,db} from '@/lib/server';
import {connectionStatus,storeKey,type Provider} from '@/lib/connections';
export const dynamic='force-dynamic';
export async function GET(req:Request){try{return Response.json(await connectionStatus(identity(req)),{headers:{'Cache-Control':'no-store'}})}catch{return Response.json({error:'Sign in to manage your connections.'},{status:401})}}
export async function POST(req:Request){let userId:string;let phase='request validation';try{userId=identity(req)}catch{return Response.json({error:'Sign in to manage your connections.'},{status:401})}try{const data=await boundedJson(req);const provider:Provider=data.provider??'marketcheck';if(!['marketcheck','openai','autodev','apify'].includes(provider))return Response.json({error:'Unsupported provider.'},{status:400});if(data.action==='disconnect'){await db().prepare('DELETE FROM connections WHERE user_id=? AND provider=?').bind(userId,provider).run();return Response.json(await connectionStatus(userId))}if(!config().CONNECTION_ENCRYPTION_KEY)return Response.json({error:'Secure storage is not ready.'},{status:503});if(typeof data.key!=='string'||data.key.trim().length<10||data.key.length>512)return Response.json({error:'Enter a valid API key.'},{status:400});phase='usage allowance';await limitUsage(userId);phase='provider verification';const apiKey=data.key.trim();let verified=false;
if(provider==='apify'){await verifyFreeAccount(apiKey);verified=true;}
else if(provider==='marketcheck'){const u=new URL('https://api.marketcheck.com/v2/search/car/active');u.searchParams.set('api_key',apiKey);u.searchParams.set('rows','0');u.searchParams.set('car_type','used');const res=await fetch(u,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(15000)});if(!res.ok)return Response.json({error:res.status===401||res.status===403?'This key does not have inventory access. Check your MarketCheck key and subscription.':`MarketCheck could not verify this connection (${res.status}). Check your plan or try again.`},{status:400});const result=record(await res.json());verified=Array.isArray(result.listings)||typeof result.num_found==='number';}
else if(provider==='autodev'){const res=await fetch('https://api.auto.dev/listings?limit=1&retailListing.used=true',{headers:{Authorization:`Bearer ${apiKey}`,Accept:'application/json'},signal:AbortSignal.timeout(18000)});if(!res.ok)return Response.json({error:res.status===429?'Auto.dev quota or rate limit reached. Check your account.':`Auto.dev inventory access could not be verified (${res.status}). Check your key and account.`},{status:400});const result=record(await res.json());verified=Array.isArray(result.data);}
else{const res=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},signal:AbortSignal.timeout(20000),body:JSON.stringify({model:config().OPENAI_MODEL||'gpt-4.1-mini',messages:[{role:'user',content:'Reply OK.'}],max_tokens:3,store:false})});if(!res.ok)return Response.json({error:res.status===429?'OpenAI reported a quota or rate limit. Check API billing or retry later.':res.status===401?'OpenAI rejected this key. Please check it.':`OpenAI model access could not be verified (${res.status}).`},{status:400});const result=record(await res.json());verified=Array.isArray(result.choices)&&result.choices.length>0;}
if(!verified)return Response.json({error:'Unexpected provider response. The key was not saved.'},{status:502});phase='encrypted credential storage';await storeKey(userId,provider,apiKey);phase='connection status';return Response.json({...await connectionStatus(userId),message:provider==='apify'?'Free marketplace account verified. Run a search to retrieve Cars.com, CarGurus, TrueCar and regional Craigslist and selected-city Facebook results. AutoTrader uses the separate MarketCheck connection.':provider==='openai'?'AI conversation is connected. Your listing sources are checked separately.':provider==='autodev'?'Auto.dev dealer inventory access verified. Run a search to retrieve current listings.':'Dealer inventory access verified. Run a search to check listings and private-seller access.'},{headers:{'Cache-Control':'no-store'}})}catch(e){return Response.json({error:e instanceof MarketplaceError?e.message:`Connection failed during ${phase}. Please retry; no key is returned or logged.`},{status:400})}}
